main:
  ref/new/act zmp:
    legends:
      - { key: st_originRefZmp, id: [0-1] }
      - { key: st_originNewZmp, id: [0-1] }
      - { key: st_originActZmp, id: [0-1] }

  ref/act z rforce:
    legends:
      # - { key: abc_rfsensor, id: [2] }
      - { key: rmfo_off_rfsensor, id: [2] }
      - { key: st_ref_rfsensor, id: [2] }
    newline: false

  ref/act z lforce:
    legends:
      # - { key: abc_lfsensor, id: [2] }
      - { key: rmfo_off_lfsensor, id: [2] }
      - { key: st_ref_lfsensor, id: [2] }

  ref/act rmoment:
    legends:
      - { key: rmfo_off_rfsensor, id: [3] }
      - { key: rmfo_off_rfsensor, id: [4] }
      - { key: st_ref_rfsensor, id: [3] }
      - { key: st_ref_rfsensor, id: [4] }
    newline: false

  ref/act lmoment:
    legends:
      - { key: rmfo_off_lfsensor, id: [3] }
      - { key: rmfo_off_lfsensor, id: [4] }
      - { key: st_ref_lfsensor, id: [3] }
      - { key: st_ref_lfsensor, id: [4] }


  # act base rpy:
  #   legends:
  #     - { key: st_actBaseRpy, id: [0-1] }

  # ref/act cog (0,2):
  #   legends:
  #     - { key: st_originRefCog, id: [0,2]}
  #     - { key: st_originActCog, id: [0,2]}

  # ref/act cogvel (0,2):
  #   legends:
  #     - { key: st_originRefCogVel, id: [0,2]}
  #     - { key: st_originActCogVel, id: [0,2]}

  contact:
    legends:
      - { key: abc_contactStates, id: [0-1]}

  rleg torque:
    legends:
      - { key: torque, id: [0]}
      - { key: torque, id: [1]}
      - { key: torque, id: [2]}
      - { key: torque, id: [3]}
      - { key: torque, id: [4]}
      - { key: torque, id: [5]}
    newline: false

  lleg torque:
    legends:
      - { key: torque, id: [6]}
      - { key: torque, id: [7]}
      - { key: torque, id: [8]}
      - { key: torque, id: [9]}
      - { key: torque, id: [10]}
      - { key: torque, id: [11]}
