main:
  hand_position:
    legends:
      - { key: shimpei, id: [1], label: "input trajectory"}
      - { key: shimpei, id: [4], label: "output trajectory"}
    left_label: 'position [m]'
  hand_acceleration:
    legends:
      - { key: shimpei, id: [13], label: "input trajectory"}
      - { key: shimpei, id: [16], label: "output trajectory"}
    left_label: 'acceleration [m/s^2]'
  misalignment:
    legends:
      - { key: shimpei_misalignment_norm, id: [0], label: "misalignment"}
    left_label: 'length [m]'
