main:
  force:
    legends:
      - { key: shimpei, id: [0], label: "r_x"}
      - { key: shimpei, id: [1], label: "r_y"}
      - { key: shimpei, id: [2], label: "r_z"}
      - { key: shimpei, id: [3], label: "l_x"}
      - { key: shimpei, id: [4], label: "l_y"}
      - { key: shimpei, id: [5], label: "l_z"}
  weight:
    legends:
      - { key: shimpei, id: [6], label: "box weight"}
  box_cog:
    legends:
      - { key: shimpei, id: [7-8], label: "force_box_pos"}
      - { key: shimpei, id: [9-10], label: "camera_box_pos"}
  joint15:
    legends:
      - { key: shimpei, id: [12], label: "diff"}
      - { key: shimpei, id: [13], label: "diff"}

