main:
  misalignment:
    legends:
      - { key: shimpei_misalignment_norm, id: [0], label: "misalignment"}
    left_label: 'misalignment [m]'
  misalignment2:
    legends:
      - { key: shimpei_misalignment_norm2, id: [0], label: "misalignment"}
    left_label: 'misalignment [m]'
