main:
  pos:
    legends:
      - { key: shimpei, id: [0], label: "xrefk_x"}
      - { key: shimpei, id: [1], label: "xrefk_y"}
      - { key: shimpei, id: [2], label: "xrefk_z"}
      - { key: shimpei, id: [3], label: "xk_x"}
      - { key: shimpei, id: [4], label: "xk_y"}
      - { key: shimpei, id: [5], label: "xk_z"}
  acc:
    legends:
      - { key: shimpei, id: [12], label: "xrefddk_x"}
      - { key: shimpei, id: [13], label: "xrefddk_y"}
      - { key: shimpei, id: [14], label: "xrefddk_z"}
      - { key: shimpei, id: [15], label: "xddk_x"}
      - { key: shimpei, id: [16], label: "xddk_y"}
      - { key: shimpei, id: [17], label: "xddk_z"}
  acc_after_only:
    legends:
      - { key: shimpei, id: [15], label: "xddk_x"}
      - { key: shimpei, id: [16], label: "xddk_y"}
      - { key: shimpei, id: [17], label: "xddk_z"}
  omega:
    legends:
      - { key: shimpei, id: [18], label: "xddk_x"}
      - { key: shimpei, id: [19], label: "xddk_y"}
      - { key: shimpei, id: [20], label: "xddk_z"}
      - { key: shimpei, id: [21], label: "xrefddk_x"}
      - { key: shimpei, id: [22], label: "xrefddk_y"}
      - { key: shimpei, id: [23], label: "xrefddk_z"}
  weight:
    legends:
      - { key: shimpei, id: [6], label: "box weight"}
  box_cog:
    legends:
      - { key: shimpei, id: [7-8], label: "force_box_pos"}
      - { key: shimpei, id: [9-10], label: "camera_box_pos"}
  misalignment:
    legends:
      - { key: shimpei, id: [24], label: "x"}
      - { key: shimpei, id: [25], label: "y"}
      - { key: shimpei, id: [26], label: "z"}
  hand_diff:
    legends:
      - { key: shimpei, id: [27], label: "x"}
      - { key: shimpei, id: [28], label: "y"}
  box_pos_x:
    legends:
      - { key: shimpei_offset, id: [7], label: "force_sensor"}
      - { key: shimpei_offset, id: [9], label: "camera"}
  box_pos_y:
    legends:
      - { key: shimpei_offset, id: [8], label: "force_sensor"}
      - { key: shimpei_offset, id: [10], label: "camera"}
