"joint_angle":
  "log": [['sh_qOut'], ['abc_q'], ['st_q']]
  "func": ['plot_rad2deg','plot_rad2deg','plot_rad2deg']
  "arg_index": [[0], [0], [0]]

"ZMP":
  "log": [['st_zmp']]
  "arg_index": [[0]]

"COP":
  "log": [['st_allRefWrench'],['abc_rfsensor','abc_lfsensor','abc_rfsensor','abc_lfsensor'],['rmfo_off_rfsensor','rmfo_off_lfsensor','rmfo_off_rhsensor','rmfo_off_lhsensor']]
  "func": ['plot_COP','plot_COP','plot_COP']
  "key": ['ST ref COP','ABC ref COP','act COP']
  "arg_index": [[0],[1],[1]]

"Fz":
  "log": [['rmfo_off_rfsensor'],['rmfo_off_lfsensor'],['rmfo_off_rhsensor'],['rmfo_off_lhsensor']]
  "key": ['RLEG','LLEG','RARM','LARM']
  "arg_index": [[0],[0],[0],[0]]

"zmp":
  "log": [['abc_zmpOut'],['st_originRefZmp'],['st_originNewZmp'],['st_originActZmp']]
  "arg_index": [[0],[0],[0],[0]]