main:
  abs ref cog/zmp:
    legends:
      # - { key: abs_refzmp, id: [0]}
      - { key: abs_refzmp, id: [0]}
      # - { key: abs_refzmp, id: [2]}
      - { key: tmp, id: [0]}
      - { key: tmp, id: [2]}
      - { key: tmp, id: [3]}
      - { key: tmp, id: [4]}
      - { key: abc_cogOut, id: [0]}

  abs ref cog/zmp2:
    legends:
      # - { key: abs_refzmp, id: [0]}
      - { key: abs_refzmp, id: [1]}
      # - { key: abs_refzmp, id: [2]}
      - { key: tmp, id: [1]}
      - { key: tmp, id: [2]}
      - { key: tmp, id: [3]}
      - { key: tmp, id: [5]}
      - { key: abc_cogOut, id: [1]}

  # zmp:
  #   legends:
  #     - { key: st_tmpCogValues, id: [0,1]}

  # tmp_cog2:
  #   legends:
  #     - { key: st_tmpCogValues, id: [3,4]}

  # cotact_states:
  #   legends:
  #     - { key: st_tmpCogValues, id: [6]}
  #     - { key: st_tmpCogValues, id: [7]}
  #     - { key: st_tmpCogValues, id: [8]}
  #   newline: false
  # cogvel y:
  #   legends:
  #     - { key: st_tmpCogValues, id: [5]}

  # tmp_act_zmp:
  #   legends:
  #     - { key: st_tmpCogValues, id: [9,10]}
  #     - { key: st_zmp, id: [0,1]}

