main:
  abs ref cog/zmp:
    legends:
      - { key: abc_cogOut, id: [0,1,2]}
      - { key: abs_refzmp, id: [0,1,2]}

  act/ref cog zmp:
    legends:
      - { key: st_originActCog, id: [0-2]}
      - { key: st_originRefCog, id: [0-2]}
      - { key: st_originActZmp, id: [0-2]}
      - { key: st_originRefZmp, id: [0-2]}
      - { key: st_originNewZmp, id: [0-2]}

  act/ref cog velocity:
    legends:
      - { key: st_originActCogVel, id: [0-2]}
      - { key: st_originRefCogVel, id: [0-2]}

  act/ref root-link relative zmp:
    legends:
      - { key: st_zmp, id: [0-1] }
      - { key: abc_zmpOut, id: [0-1] }

  base rpy:
    legends:
      - { key: st_actBaseRpy, id: [0-1] }
      - { key: sh_baseRpyOut, id: [0-1] }
      - { key: st_currentBaseRpy , id: [0-1] }

  # act/ref force:
  #   legends:
  #     - { key: rmfo_off_rfsensor, id: [0-2] }
  #     - { key: rmfo_off_lfsensor, id: [0-2] }
  #     - { key: st_ref_rfsensor, id: [0-2] }
  #     - { key: st_ref_lfsensor, id: [0-2] }

  # act/ref moment:
  #   legends:
  #     - { key: rmfo_off_rfsensor, id: [3-5] }
  #     - { key: rmfo_off_lfsensor, id: [3-5] }
  #     - { key: st_ref_rfsensor, id: [3-5] }
  #     - { key: st_ref_lfsensor, id: [3-5] }

  cp:
    legends:
      - { key: st_RefCp, id: [0,1]}
      - { key: st_ActCp, id: [0,1]}
