main:
  act/ref force:
    legends:
      - { key: rmfo_off_rfsensor, id: [2] }
      - { key: rmfo_off_lfsensor, id: [2] }
      - { key: st_ref_rfsensor, id: [2] }
      - { key: st_ref_lfsensor, id: [2] }
    newline: False

  act/rfu_ref force:
    legends:
      - { key: rmfo_off_rfsensor, id: [2] }
      - { key: rmfo_off_lfsensor, id: [2] }
      - { key: rfu_ref_rfsensorOut, id: [2] }
      - { key: rfu_ref_lfsensorOut, id: [2] }

  act base rpy:
    legends:
      - { key: st_actBaseRpy, id: [0-1] }

  cog/zmp error:
    legends:
      - { key: cog_diff, id: [0-1] }
      - { key: zmp_diff, id: [0-1] }

  abs ref zmp:
    legends:
      - { key: abs_refzmp, id: [0-1]}
