extend:
  ../../common_plot.yaml

sh_qOut:
  func: plot_rad2deg
  data:
    - { log: sh_qOut, column: [0-11] }

abc_q:
  func: plot_rad2deg
  data:
    - { log: abc_q, column: [0-11] }

st_q:
  func: plot_rad2deg
  data:
    - { log: st_q, column: [0-11] }

st_qSTRef:
  func: plot_rad2deg
  data:
    - { log: st_qSTRef, column: [0-11] }

RobotHardware0_q:
  func: plot_rad2deg
  data:
    - { log: RobotHardware0_q, column: [0-11] }

rh_st_diff:
  func: plot_rh_q_st_q
  data:
    - { log: RobotHardware0_q, column: [0-11] }
    - { log: st_q, column: [0-11] }

abs_enc_diff:
  func: plot_abs_enc
  data:
    - { log: RobotHardware0_servoState, column: [0-11] }
    - { log: RobotHardware0_servoState, column: [0-11] }

sh_rfsensorOut:
  data:
    - { log: sh_rfsensorOut, column: [0-5] }

RobotHardware0_rfsensor:
  data:
    - { log: RobotHardware0_rfsensor, column: [0-5] }

rmfo_off_rfsensor:
  data:
    - { log: rmfo_off_rfsensor, column: [0-5] }

sh_lfsensorOut:
  data:
    - { log: sh_lfsensorOut, column: [0-5] }

RobotHardware0_lfsensor:
  data:
    - { log: RobotHardware0_lfsensor, column: [0-5] }

rmfo_off_lfsensor:
  data:
    - { log: rmfo_off_lfsensor, column: [0-5] }

current:
  func: plot_current
  data:
    - { log: RobotHardware0_servoState, column: [0,1,2,3,4,5] }

imu_gsensor:
  data:
    - { log: RobotHardware0_gsensor, column: [0,1,2] }

imu_gyrometer:
  data:
    - { log: RobotHardware0_gyrometer, column: [0,1,2] }

motor_temp:
  func: plot_motor_temp
  data:
    - { log: RobotHardware0_servoState, column: [0,1,2,3,4,5] }

motor_outer_temp:
  func: plot_motor_outer_temp
  data:
    - { log: RobotHardware0_servoState, column: [0,1,2,3,4,5] }

comp:
  func: plot_comp
  data:
    -  { log: st_allEEComp, column: [0, 1, 2, 3, 4, 5] }

watt:
  func: plot_watt
  data:
    - { log: RobotHardware0_dq, column: [0,1,2,3,4,5]  }
    - { log: RobotHardware0_tau, column: [0,1,2,3,4,5] }
ServoState:
  func: plot_servostate
  data:
    - { log: RobotHardware0_servoState, column: [0,1,2,3,4,5] }

12V:
  func: plot_12V
  data:
    - { log: RobotHardware0_servoState, column: [0,1,2,3,4,5] }

80V:
  func: plot_80V
  data:
    - { log: RobotHardware0_servoState, column: [0,1,2,3,4,5] }

pgain:
  func: plot_pgain
  data:
    - { log: RobotHardware0_servoState, column: [0-11] }

dgain:
  func: plot_dgain
  data:
    - { log: RobotHardware0_servoState, column: [0-11] }

st_zmp:
  data:
    - { log: st_zmp, column: [0,1] }
