- title: cog
  legends:
    - { key: st_originActCog, id: [0-2]}
    - { key: st_originRefCog, id: [0-2]}
    - { key: st_originActZmp, id: [0-2]}
    - { key: st_originRefZmp, id: [0-2]}
    - { key: st_originNewZmp, id: [0-2]}

- title: force
  legends:
    - { key: rmfo_off_rfsensor, id: [0-2] }
    - { key: rmfo_off_lfsensor, id: [0-2] }
    - { key: st_ref_rfsensor, id: [0-2] }
    - { key: st_ref_lfsensor, id: [0-2] }


- title: moment
  legends:
    - { key: rmfo_off_rfsensor, id: [3-5] }
    - { key: rmfo_off_lfsensor, id: [3-5] }
    - { key: st_ref_rfsensor, id: [3-5] }
    - { key: st_ref_lfsensor, id: [3-5] }

