main:
  # lleg current:
  #   legends:
  #     - { key: RobotHardware0_tau, id: [0], label: crotch-yaw }
  #     - { key: RobotHardware0_tau, id: [37], label: crotch-inner }
  #     - { key: RobotHardware0_tau, id: [38], label: crotch-outer }
  #     - { key: RobotHardware0_tau, id: [39], label: knee }
  #     - { key: RobotHardware0_tau, id: [40], label: ankle-inner }
  #     - { key: RobotHardware0_tau, id: [41], label: ankle-outer }
  # lleg torque:
  #   legends:
  #     - { key: cta_tau, id: [0], label: crotch yaw }
  #     - { key: cta_tau, id: [1], label: crotch pitch }
  #     - { key: cta_tau, id: [2], label: crotch roll }
  #     - { key: cta_tau, id: [3], label: knee }
  #     - { key: cta_tau, id: [4], label: ankle roll}
  #     - { key: cta_tau, id: [5], label: ankle pitch }
  # rleg current:
  #   legends:
  #     - { key: RobotHardware0_tau, id: [8], label: crotch-yaw }
  #     - { key: RobotHardware0_tau, id: [32], label: crotch-inner }
  #     - { key: RobotHardware0_tau, id: [33], label: crotch-outer }
  #     - { key: RobotHardware0_tau, id: [34], label: knee }
  #     - { key: RobotHardware0_tau, id: [35], label: ankle-inner }
  #     - { key: RobotHardware0_tau, id: [36], label: ankle-outer }
  # rleg torque:
  #   legends:
  #     - { key: cta_tau, id: [8], label: crotch yaw }
  #     - { key: cta_tau, id: [9], label: crotch pitch }
  #     - { key: cta_tau, id: [10], label: crotch roll }
  #     - { key: cta_tau, id: [11], label: knee }
  #     - { key: cta_tau, id: [12], label: ankle roll}
  #     - { key: cta_tau, id: [13], label: ankle pitch }
  larm torque:
    legends:
      - { key: cta_tau, id: [16], label: l sholder p }
      - { key: cta_tau, id: [17], label: l shoulder r }
      - { key: cta_tau, id: [18], label: l shoulder y }
      - { key: cta_tau, id: [19], label: l elbow p}
      - { key: cta_tau, id: [20], label: l elbow y}
      - { key: cta_tau, id: [21], label: l wrist p }
      - { key: cta_tau, id: [22], label: l wrist y }
      - { key: cta_tau, id: [23], label: l hand }
  larm current:
    legends:
      - { key: RobotHardware0_tau, id: [16], label: l shoulder p }
      - { key: RobotHardware0_tau, id: [17], label: l shoulder r }
      - { key: RobotHardware0_tau, id: [18], label: l shoulder y }
      - { key: RobotHardware0_tau, id: [45], label: l elbow p}
      - { key: RobotHardware0_tau, id: [20], label: l elbow y}
      - { key: RobotHardware0_tau, id: [21], label: l wrist p }
      - { key: RobotHardware0_tau, id: [22], label: l wrist y }
      - { key: RobotHardware0_tau, id: [23], label: l hand }

