main:
 lleg_joint_angle:
   legends:
     - { key: st_q, id: [0-5]}
     - { key: RobotHardware0_q, id: [0-5] }

 rleg_joint_angle:
   legends:
     - { key: st_q, id: [8-13]}
     - { key: RobotHardware0_q, id: [8-13] }